<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="26" passed="19" failed="7" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-12-30T15:55:54 IST" name="Default suite" finished-at="2023-12-30T15:57:29 IST" duration-ms="94769">
    <groups>
    </groups>
    <test started-at="2023-12-30T15:55:54 IST" name="Default test" finished-at="2023-12-30T15:57:29 IST" duration-ms="94769">
      <class name="tests.AutomationTestCase">
        <test-method is-config="true" signature="setup()[pri:0, instance:tests.AutomationTestCase@7c37508a]" started-at="2023-12-30T15:55:54 IST" name="setup" finished-at="2023-12-30T15:56:10 IST" duration-ms="15754" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="resgistrationpage_testcase()[pri:1, instance:tests.AutomationTestCase@7c37508a]" started-at="2023-12-30T15:56:10 IST" name="resgistrationpage_testcase" finished-at="2023-12-30T15:56:11 IST" duration-ms="985" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- resgistrationpage_testcase -->
        <test-method signature="loginuser_with_correct_crendials()[pri:2, instance:tests.AutomationTestCase@7c37508a]" started-at="2023-12-30T15:56:11 IST" name="loginuser_with_correct_crendials" finished-at="2023-12-30T15:56:11 IST" duration-ms="21" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Actual url is equal to the expected url(https://automationexercise.com/) expected [https://automationexercise.com/] but found [https://automationexercise.com/login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Actual url is equal to the expected url(https://automationexercise.com/) expected [https://automationexercise.com/] but found [https://automationexercise.com/login]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at utilities.Reusableclass.urlEquals(Reusableclass.java:31)
at pageElements.LoginUser.loginWithCorrectCred(LoginUser.java:46)
at tests.AutomationTestCase.loginuser_with_correct_crendials(AutomationTestCase.java:71)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginuser_with_correct_crendials -->
        <test-method signature="loginuser_with_incorrect_crendials()[pri:3, instance:tests.AutomationTestCase@7c37508a]" started-at="2023-12-30T15:56:11 IST" name="loginuser_with_incorrect_crendials" finished-at="2023-12-30T15:56:11 IST" duration-ms="64" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Actual url is equal to the expected url(https://automationexercise.com/) expected [https://automationexercise.com/] but found [https://automationexercise.com/login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Actual url is equal to the expected url(https://automationexercise.com/) expected [https://automationexercise.com/] but found [https://automationexercise.com/login]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at utilities.Reusableclass.urlEquals(Reusableclass.java:31)
at pageElements.LoginUser.loginWithInCorrectCred(LoginUser.java:77)
at tests.AutomationTestCase.loginuser_with_incorrect_crendials(AutomationTestCase.java:77)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginuser_with_incorrect_crendials -->
        <test-method signature="logout_user()[pri:4, instance:tests.AutomationTestCase@7c37508a]" started-at="2023-12-30T15:56:11 IST" name="logout_user" finished-at="2023-12-30T15:56:11 IST" duration-ms="818" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout_user -->
        <test-method signature="registeruser_with_existingmail()[pri:5, instance:tests.AutomationTestCase@7c37508a]" started-at="2023-12-30T15:56:11 IST" name="registeruser_with_existingmail" finished-at="2023-12-30T15:56:12 IST" duration-ms="805" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registeruser_with_existingmail -->
        <test-method signature="contactus_form()[pri:6, instance:tests.AutomationTestCase@7c37508a]" started-at="2023-12-30T15:56:12 IST" name="contactus_form" finished-at="2023-12-30T15:56:18 IST" duration-ms="6054" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- contactus_form -->
        <test-method signature="verify_testcases_page()[pri:7, instance:tests.AutomationTestCase@7c37508a]" started-at="2023-12-30T15:56:18 IST" name="verify_testcases_page" finished-at="2023-12-30T15:56:24 IST" duration-ms="5437" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_testcases_page -->
        <test-method signature="verify_allproducts_productdetailspage()[pri:8, instance:tests.AutomationTestCase@7c37508a]" started-at="2023-12-30T15:56:24 IST" name="verify_allproducts_productdetailspage" finished-at="2023-12-30T15:56:31 IST" duration-ms="7325" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_allproducts_productdetailspage -->
        <test-method signature="search_product()[pri:9, instance:tests.AutomationTestCase@7c37508a]" started-at="2023-12-30T15:56:31 IST" name="search_product" finished-at="2023-12-30T15:56:38 IST" duration-ms="7026" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- search_product -->
        <test-method signature="verify_subscription_in_homepage()[pri:10, instance:tests.AutomationTestCase@7c37508a]" started-at="2023-12-30T15:56:38 IST" name="verify_subscription_in_homepage" finished-at="2023-12-30T15:56:43 IST" duration-ms="4807" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_subscription_in_homepage -->
        <test-method signature="verify_subscription_in_cartpage()[pri:11, instance:tests.AutomationTestCase@7c37508a]" started-at="2023-12-30T15:56:43 IST" name="verify_subscription_in_cartpage" finished-at="2023-12-30T15:56:48 IST" duration-ms="4765" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_subscription_in_cartpage -->
        <test-method signature="add_products_incart()[pri:12, instance:tests.AutomationTestCase@7c37508a]" started-at="2023-12-30T15:56:48 IST" name="add_products_incart" finished-at="2023-12-30T15:56:48 IST" duration-ms="52" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://automationexercise.com/] but found [https://automationexercise.com/view_cart#google_vignette]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://automationexercise.com/] but found [https://automationexercise.com/view_cart#google_vignette]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at pageElements.Productpage.addproducts(Productpage.java:172)
at tests.AutomationTestCase.add_products_incart(AutomationTestCase.java:131)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- add_products_incart -->
        <test-method signature="verify_product_quantity_in_cart()[pri:13, instance:tests.AutomationTestCase@7c37508a]" started-at="2023-12-30T15:56:48 IST" name="verify_product_quantity_in_cart" finished-at="2023-12-30T15:56:49 IST" duration-ms="1070" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_product_quantity_in_cart -->
        <test-method signature="Place_Order_Register_while_Checkout()[pri:14, instance:tests.AutomationTestCase@7c37508a]" started-at="2023-12-30T15:56:49 IST" name="Place_Order_Register_while_Checkout" finished-at="2023-12-30T15:56:50 IST" duration-ms="1111" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Place_Order_Register_while_Checkout -->
        <test-method signature="Place_Order_Register_before_Checkout()[pri:15, instance:tests.AutomationTestCase@7c37508a]" started-at="2023-12-30T15:56:50 IST" name="Place_Order_Register_before_Checkout" finished-at="2023-12-30T15:56:50 IST" duration-ms="10" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Actual url is equal to the expected url(https://automationexercise.com/) expected [https://automationexercise.com/] but found [https://automationexercise.com/view_cart#google_vignette]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Actual url is equal to the expected url(https://automationexercise.com/) expected [https://automationexercise.com/] but found [https://automationexercise.com/view_cart#google_vignette]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at utilities.Reusableclass.urlEquals(Reusableclass.java:31)
at pageElements.RegisterUser.homepagevisibiblity(RegisterUser.java:57)
at pageElements.PlaceOrderPage.register_beforecheckout(PlaceOrderPage.java:166)
at tests.AutomationTestCase.Place_Order_Register_before_Checkout(AutomationTestCase.java:149)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Place_Order_Register_before_Checkout -->
        <test-method signature="Place_Order_login_before_Checkout()[pri:16, instance:tests.AutomationTestCase@7c37508a]" started-at="2023-12-30T15:56:50 IST" name="Place_Order_login_before_Checkout" finished-at="2023-12-30T15:56:50 IST" duration-ms="9" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Actual url is equal to the expected url(https://automationexercise.com/) expected [https://automationexercise.com/] but found [https://automationexercise.com/view_cart#google_vignette]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Actual url is equal to the expected url(https://automationexercise.com/) expected [https://automationexercise.com/] but found [https://automationexercise.com/view_cart#google_vignette]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at utilities.Reusableclass.urlEquals(Reusableclass.java:31)
at pageElements.PlaceOrderPage.login_beforecheckout(PlaceOrderPage.java:225)
at tests.AutomationTestCase.Place_Order_login_before_Checkout(AutomationTestCase.java:155)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Place_Order_login_before_Checkout -->
        <test-method signature="remove_product_from_cart()[pri:17, instance:tests.AutomationTestCase@7c37508a]" started-at="2023-12-30T15:56:50 IST" name="remove_product_from_cart" finished-at="2023-12-30T15:56:51 IST" duration-ms="1109" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- remove_product_from_cart -->
        <test-method signature="view_category_products()[pri:18, instance:tests.AutomationTestCase@7c37508a]" started-at="2023-12-30T15:56:51 IST" name="view_category_products" finished-at="2023-12-30T15:56:52 IST" duration-ms="1076" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- view_category_products -->
        <test-method signature="view_and_cart_brand_products()[pri:19, instance:tests.AutomationTestCase@7c37508a]" started-at="2023-12-30T15:56:52 IST" name="view_and_cart_brand_products" finished-at="2023-12-30T15:56:56 IST" duration-ms="3461" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- view_and_cart_brand_products -->
        <test-method signature="prod_search_verify_cart_afterlogin()[pri:20, instance:tests.AutomationTestCase@7c37508a]" started-at="2023-12-30T15:56:56 IST" name="prod_search_verify_cart_afterlogin" finished-at="2023-12-30T15:57:06 IST" duration-ms="10101" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- prod_search_verify_cart_afterlogin -->
        <test-method signature="add_review_in_product()[pri:21, instance:tests.AutomationTestCase@7c37508a]" started-at="2023-12-30T15:57:06 IST" name="add_review_in_product" finished-at="2023-12-30T15:57:17 IST" duration-ms="11695" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- add_review_in_product -->
        <test-method signature="add_tocart_from_recommandeditems()[pri:22, instance:tests.AutomationTestCase@7c37508a]" started-at="2023-12-30T15:57:17 IST" name="add_tocart_from_recommandeditems" finished-at="2023-12-30T15:57:21 IST" duration-ms="3832" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- add_tocart_from_recommandeditems -->
        <test-method signature="verify_address_details_in_checkoutpage()[pri:23, instance:tests.AutomationTestCase@7c37508a]" started-at="2023-12-30T15:57:21 IST" name="verify_address_details_in_checkoutpage" finished-at="2023-12-30T15:57:21 IST" duration-ms="41" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Actual url is equal to the expected url(https://automationexercise.com/) expected [https://automationexercise.com/] but found [https://automationexercise.com/view_cart]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Actual url is equal to the expected url(https://automationexercise.com/) expected [https://automationexercise.com/] but found [https://automationexercise.com/view_cart]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at utilities.Reusableclass.urlEquals(Reusableclass.java:31)
at pageElements.PlaceOrderPage.addressdetails_verify(PlaceOrderPage.java:291)
at tests.AutomationTestCase.verify_address_details_in_checkoutpage(AutomationTestCase.java:197)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_address_details_in_checkoutpage -->
        <test-method signature="download_invoice_after_purchase_order()[pri:24, instance:tests.AutomationTestCase@7c37508a]" started-at="2023-12-30T15:57:21 IST" name="download_invoice_after_purchase_order" finished-at="2023-12-30T15:57:21 IST" duration-ms="9" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Actual url is equal to the expected url(https://automationexercise.com/) expected [https://automationexercise.com/] but found [https://automationexercise.com/view_cart]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Actual url is equal to the expected url(https://automationexercise.com/) expected [https://automationexercise.com/] but found [https://automationexercise.com/view_cart]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at utilities.Reusableclass.urlEquals(Reusableclass.java:31)
at pageElements.PlaceOrderPage.downloadinvoice(PlaceOrderPage.java:337)
at tests.AutomationTestCase.download_invoice_after_purchase_order(AutomationTestCase.java:203)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- download_invoice_after_purchase_order -->
        <test-method signature="scroll_up_and_down_using_arrowbutton()[pri:25, instance:tests.AutomationTestCase@7c37508a]" started-at="2023-12-30T15:57:21 IST" name="scroll_up_and_down_using_arrowbutton" finished-at="2023-12-30T15:57:24 IST" duration-ms="3041" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- scroll_up_and_down_using_arrowbutton -->
        <test-method signature="scroll_up_and_down_withour_using_arrowbutton()[pri:26, instance:tests.AutomationTestCase@7c37508a]" started-at="2023-12-30T15:57:24 IST" name="scroll_up_and_down_withour_using_arrowbutton" finished-at="2023-12-30T15:57:29 IST" duration-ms="4212" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- scroll_up_and_down_withour_using_arrowbutton -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:tests.AutomationTestCase@7c37508a]" started-at="2023-12-30T15:57:29 IST" name="closeBrowser" finished-at="2023-12-30T15:57:29 IST" duration-ms="209" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- tests.AutomationTestCase -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
